# This file is managed by github-terraform. Manual changes will be overwritten.
# To modify it, edit orgs/pantheon-systems/files/dependabot/custom/pauditd.yml
# in https://github.com/pantheon-systems/github-terraform
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
