version: 2

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

linters:
  enable:
    - errcheck
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unparam
  settings:
    gocyclo:
      min-complexity: 15
    revive:
      ignore-generated-header: true
    errcheck:
      check-type-assertions: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - text: "cyclomatic complexity"
      linters:
        - gocyclo