version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports

linters:
  enable:
    - errcheck
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - unparam
  settings:
    gocyclo:
      min-complexity: 15
    errcheck:
      check-type-assertions: true