version: 2

project_name: pauditd

builds:
  -
    binary: pauditd
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w
    goos:
      - linux
    goarch:
      - amd64

archives:
  -
    id: tarball
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

nfpms:
  -
    formats:
      - rpm
    vendor: "Pantheon Systems"
    homepage: "https://github.com/pantheon-systems/pauditd"
    maintainer: engineering <engineering@pantheon.io>
    description: "go alternative to auditd"
    license: MIT
    bindir: /usr/local/bin
    overrides:
      rpm:
        file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Timestamp }}-{{ .Arch }}"

## build and push
dockers:
  -
    dockerfile: Dockerfile
    ids:
      - pauditd
    goos: linux
    goarch: amd64
    image_templates:
      - "quay.io/getpantheon/pauditd:{{ .Tag }}"                  # v1.0.0
      - "quay.io/getpantheon/pauditd:v{{ .Major }}"               # v1
      - "quay.io/getpantheon/pauditd:v{{ .Major }}.{{ .Minor }}"  # v1.0
      - "quay.io/getpantheon/pauditd:latest"

# GitHub Releases
release:
  github:
      owner: pantheon-systems
      name: pauditd
      draft: false      # Set to true if you want to manually review before publishing
      prerelease: false # Set to true for pre-releases