name: Build and Release

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: "1.24.x"
  USE_GO_CACHE: false
  IS_MAIN_BRANCH: ${{ github.ref == 'refs/heads/master' }}

jobs:
  deps:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: read
    name: Install dependencies
    steps:
      - name: "Checkout code"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Setup Go and Cache Modules"
        uses: ./.github/actions/setup-go-and-cache
        with:
          go-version: ${{ env.GO_VERSION }}
          use-cache: ${{ env.USE_GO_CACHE }}

      - name: "Download dependencies"
        run: go mod download
        working-directory: .

        env:
          GO111MODULE: on

  format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [deps]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Setup Go and Cache Modules"
        uses: ./.github/actions/setup-go-and-cache
        with:
          go-version: ${{ env.GO_VERSION }}
          use-cache: ${{ env.USE_GO_CACHE }}

      - name: "Tidy and Format"
        run: |
          go mod tidy
          go fmt ./...
        working-directory: .

      - name: "Check for changes"
        id: changed-files
        uses: tj-actions/verify-changed-files@a1c6acee9df209257a246f2cc6ae8cb6581c1edf # v20.0.4

      - name: "Fail if formatting modified files"
        if: steps.changed-files.outputs.files_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.changed_files }}
        run: |
          echo "The following files have changed:"
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file"
          done
          exit 1

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [deps]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Setup Go and Cache Modules"
        uses: ./.github/actions/setup-go-and-cache
        with:
          go-version: ${{ env.GO_VERSION }}
          use-cache: ${{ env.USE_GO_CACHE }}

      - name: "Run golangci-lint"
        uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9.3.0
        with:
          version: v2.1
          working-directory: .

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    needs: [deps]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Setup Go and Cache Modules"
        uses: ./.github/actions/setup-go-and-cache
        with:
          go-version: ${{ env.GO_VERSION }}
          use-cache: ${{ env.USE_GO_CACHE }}

      - name: "Install go-ctrf-json-reporter"
        run: go install github.com/ctrf-io/go-ctrf-json-reporter/cmd/go-ctrf-json-reporter@latest
        working-directory: .

      - name: "Run Go tests and generate CTRF"
        continue-on-error: true
        run: |
          go test -v -json ./... | go-ctrf-json-reporter -output ctrf-report.json
        working-directory: .

      - name: "Report results to GitHub"
        uses: ctrf-io/github-test-reporter@7974087018bf4857cf5a9d78723e152038c3fa31 # v1.3.0
        with:
          report-path: "./ctrf-report.json"

      - name: "Abort if tests failed"
        run: |
          if jq -r '.results.tests[] | select(.status == "failed") | .name' ctrf-report.json | grep .; then
            echo "❌ Tests failed"
            exit 1
          fi
        working-directory: .

  goreleaser-check:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: "Check goreleaser's Configuration"
        uses: ./.github/actions/run-goreleaser
        with:
          args: check
          workdir: .

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: [deps, goreleaser-check]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Setup Go and Cache Modules"
        uses: ./.github/actions/setup-go-and-cache
        with:
          go-version: ${{ env.GO_VERSION }}
          use-cache: ${{ env.USE_GO_CACHE }}

      - name: "Build Artifacts"
        uses: ./.github/actions/run-goreleaser
        with:
          args: release --clean --snapshot --skip=publish
          workdir: .

      - name: "Upload Build Artifacts"
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: build-artifacts
          path: |
            dist/**
            !dist/*.txt

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    needs: [format, lint, test, build]
    steps:
      - name: "Checkout code"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: "Fetch tags"
        run: git fetch --tags --force

      - name: "Install and Run autotag"
        if: env.IS_MAIN_BRANCH == 'true'
        uses: pantheon-systems/action-autotag@eed8cb09a4c1b2c2f19fea63451749aaea502bd9 # v1.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Download RPM Artifacts"
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: build-artifacts
          path: dist

      - name: "Setup Ruby"
        uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1.327.0
        with:
          ruby-version: "3.1" # or another version as required

      - name: "Install Package Cloud"
        run: gem install package_cloud

      - name: "Publish GitHub Release"
        if: env.IS_MAIN_BRANCH == 'true'
        uses: ./.github/actions/run-goreleaser
        with:
          args: release --clean --skip=nfpm,docker
          workdir: .

      # - name: GitHub Token
      #   id: get-package-cloud-token
      #   uses: pantheon-systems/action-get-gsm-secret@e1aa1fc741823593ded25d9230bd531919638a52 # v0.1.0
      #   with:
      #     # Full secret path in Vault would be `secret/ci-shared/package-cloud`
      #     secret_name: package-cloud
      #     scope: shared

      # - name: "Publish RPMs to PackageCloud"
      #   if: env.IS_MAIN_BRANCH == 'true'
      #   run: |
      #     for ver in 22 28 29 el/7; do
      #       package_cloud push pantheon/public/fedora/$ver ./dist/*.rpm
      #     done
      #   env:
      #     PACKAGECLOUD_TOKEN: ${{ steps.get-package-cloud-token.outputs.secret }}
